/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class basis {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected basis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(basis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        w_e_boneJNI.delete_basis(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public basis(SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t position_vector, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t u, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t r, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t t) {
    this(w_e_boneJNI.new_basis(SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(position_vector), SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(u), SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(r), SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(t)), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t get_u() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t(w_e_boneJNI.basis_get_u(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t get_r() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t(w_e_boneJNI.basis_get_r(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t get_t() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t(w_e_boneJNI.basis_get_t(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t get_position_vector() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t(w_e_boneJNI.basis_get_position_vector(swigCPtr, this), true);
  }

  public void set_u(SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t u) {
    w_e_boneJNI.basis_set_u(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(u));
  }

  public void set_r(SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t r) {
    w_e_boneJNI.basis_set_r(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(r));
  }

  public void set_t(SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t t) {
    w_e_boneJNI.basis_set_t(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(t));
  }

  public void set_position_vector(SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t position_vector) {
    w_e_boneJNI.basis_set_position_vector(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__vec3d_t.getCPtr(position_vector));
  }

  public String str() {
    return w_e_boneJNI.basis_str(swigCPtr, this);
  }

}
