/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maenitejava;

public class DeviceInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public DeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeNiteJavaJNI.delete_DeviceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeviceInfo(String device_name, String device_serial, String vendor_name, String creation_info) {
    this(MaeNiteJavaJNI.new_DeviceInfo(device_name, device_serial, vendor_name, creation_info), true);
  }

  public String getDeviceName() {
    return MaeNiteJavaJNI.DeviceInfo_getDeviceName(swigCPtr, this);
  }

  public String getDeviceSerial() {
    return MaeNiteJavaJNI.DeviceInfo_getDeviceSerial(swigCPtr, this);
  }

  public String getVendorName() {
    return MaeNiteJavaJNI.DeviceInfo_getVendorName(swigCPtr, this);
  }

  public String getCreationInfo() {
    return MaeNiteJavaJNI.DeviceInfo_getCreationInfo(swigCPtr, this);
  }

  public String str() {
    return MaeNiteJavaJNI.DeviceInfo_str(swigCPtr, this);
  }

}
