/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maenitejava;

public class GeneralSkeletonVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GeneralSkeletonVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeneralSkeletonVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeNiteJavaJNI.delete_GeneralSkeletonVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeneralSkeletonVector() {
    this(MaeNiteJavaJNI.new_GeneralSkeletonVector__SWIG_0(), true);
  }

  public GeneralSkeletonVector(long n) {
    this(MaeNiteJavaJNI.new_GeneralSkeletonVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeNiteJavaJNI.GeneralSkeletonVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeNiteJavaJNI.GeneralSkeletonVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeNiteJavaJNI.GeneralSkeletonVector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return MaeNiteJavaJNI.GeneralSkeletonVector_empty(swigCPtr, this);
  }

  public void clear() {
    MaeNiteJavaJNI.GeneralSkeletonVector_clear(swigCPtr, this);
  }

  public void pushBack(SWIGTYPE_p_mae__general_skeleton x) {
    MaeNiteJavaJNI.GeneralSkeletonVector_pushBack(swigCPtr, this, SWIGTYPE_p_mae__general_skeleton.getCPtr(x));
  }

  public SWIGTYPE_p_mae__general_skeleton get(int i) {
    long cPtr = MaeNiteJavaJNI.GeneralSkeletonVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_mae__general_skeleton(cPtr, true);
  }

  public void set(int i, SWIGTYPE_p_mae__general_skeleton val) {
    MaeNiteJavaJNI.GeneralSkeletonVector_set(swigCPtr, this, i, SWIGTYPE_p_mae__general_skeleton.getCPtr(val));
  }

}
