/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maenitejava;

public class NiteControllerVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public NiteControllerVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(NiteControllerVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeNiteJavaJNI.delete_NiteControllerVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NiteControllerVector() {
    this(MaeNiteJavaJNI.new_NiteControllerVector__SWIG_0(), true);
  }

  public NiteControllerVector(long n) {
    this(MaeNiteJavaJNI.new_NiteControllerVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeNiteJavaJNI.NiteControllerVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeNiteJavaJNI.NiteControllerVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeNiteJavaJNI.NiteControllerVector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return MaeNiteJavaJNI.NiteControllerVector_empty(swigCPtr, this);
  }

  public void clear() {
    MaeNiteJavaJNI.NiteControllerVector_clear(swigCPtr, this);
  }

  public void pushBack(NiteController x) {
    MaeNiteJavaJNI.NiteControllerVector_pushBack(swigCPtr, this, NiteController.getCPtr(x), x);
  }

  public NiteController get(int i) {
    long cPtr = MaeNiteJavaJNI.NiteControllerVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new NiteController(cPtr, true);
  }

  public void set(int i, NiteController val) {
    MaeNiteJavaJNI.NiteControllerVector_set(swigCPtr, this, i, NiteController.getCPtr(val), val);
  }

}
