branches:
  except:
    - gh-pages

skip_tags: true

image: Visual Studio 2017

clone_folder: c:\projects\MAE

clone_depth: 1

platform:
  - x64
#  - x86

configuration: Release

environment:
  matrix:
  - PACKAGE_MANAGER: MSYS2
  - PACKAGE_MANAGER: VCPKG

cache:
  - C:\ProgramData\chocolatey\bin #-> appveyor.yml
  - C:\ProgramData\chocolatey\lib #-> appveyor.yml
  - C:\tools\vcpkg\installed\ #-> appveyor.yml

for:
  -
    matrix:
      only:
        - PACKAGE_MANAGER: MSYS2
    environment:
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      MPREFIX: "/mingw64/"
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
    install:
      - cinst -y gradle maven jdk8 groovy
      - PATH C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
      - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
      - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"
      - bash -xlc "pacman --noconfirm -S --needed base-devel gradle mingw-w64-%MSYS2_ARCH%-swig"
      - bash -xlc "pacman --noconfirm -S --needed mingw-w64-%MSYS2_ARCH%-libxml++2.6 mingw-w64-%MSYS2_ARCH%-opencv mingw-w64-%MSYS2_ARCH%-boost mingw-w64-%MSYS2_ARCH%-SDL2 mingw-w64-%MSYS2_ARCH%-SDL2_image mingw-w64-%MSYS2_ARCH%-SDL2_ttf mingw-w64-%MSYS2_ARCH%-librsvg"
      - cd %APPVEYOR_BUILD_FOLDER%
      - set CHERE_INVOKING=yes
    build_script:
      - cd %APPVEYOR_BUILD_FOLDER%\libmae
      - cmake . -G "MSYS Makefiles" && make && make install
      - cd %APPVEYOR_BUILD_FOLDER%\libmae_demo
      - cmake . -G "MSYS Makefiles" && make && make install
      - cd %APPVEYOR_BUILD_FOLDER%\libmae_eventing
      - cmake . -G "MSYS Makefiles" && make && make install
  -
    matrix:
      only:
        - PACKAGE_MANAGER: VCPKG
    environment:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
    install:
      - cinst git swig gradle maven jdk8 groovy
      - cd C:\tools\vcpkg
      - git pull
      - .\bootstrap-vcpkg.bat
      - vcpkg integrate install
      - git clone https://github.com/furylynx/vcpkg-ports.git C:\tools\vcpkg-ports
      - Copy-Item "C:\tools\vcpkg-ports\ports\*" -Destination "C:\tools\vcpkg\ports\" -Recurse
      - vcpkg install opencv libxmlpp sdl2 sdl2-image sdl2-ttf boost boost-test librsvg
      - cd %APPVEYOR_BUILD_FOLDER%
    build_script:
      - cd %APPVEYOR_BUILD_FOLDER%\libmae
      - cmake . -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DMAE_STATIC=true -G "%CMAKE_GENERATOR%" -DWRAP_CSHARP=true
      - cmake --build . --target install --config Release
      - PATH C:\Progra~1\mae\bin;C:\vcpkg\installed\x64-windows\bin;%PATH%
      - cd %APPVEYOR_BUILD_FOLDER%\libmae_demo
      - cmake . -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DMAE_STATIC=true -G "%CMAKE_GENERATOR%"
      - cmake --build . --target install --config Release
      - cd %APPVEYOR_BUILD_FOLDER%\libmae_eventing
      - cmake . -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DMAE_STATIC=true -G "%CMAKE_GENERATOR%"
      - cmake --build . --target install --config Release
      - cd %APPVEYOR_BUILD_FOLDER%\samples\minimal-libmae-csharp
      - cmake . -G "Visual Studio 15 2017 Win64"
      - cmake --build . --config Release
