language: cpp
sudo: true

matrix:
  include:

    # Linux C++14 GCC builds
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - 'g++-6'
            - libopencv-dev
            - libxml++2.6-dev
            - libboost-all-dev
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev
            - swig3.0
            - openjdk-8-jdk
            - gradle
            - groovy
      env: COMPILER='g++-6' BUILD_TYPE='Release'


before_script:
  - export CXX=${COMPILER}


script:
  - cd libmae/ && cmake . && sudo make install && sudo rm install_manifest.txt && make package && cd ..
  - cd libmae_demo/ && cmake . && sudo make install && sudo rm install_manifest.txt && make package && cd ..
  - cd libmae_eventing/ && cmake . && sudo make install && sudo rm install_manifest.txt && make package && cd ..
