
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
# branches:
#   # blacklist
#   except:
#     - gh-pages

# Do not build on tags (GitHub and BitBucket)
#skip_tags: true

# Build worker image (VM template)
#image: Visual Studio 2015

# clone directory
# clone_folder: c:\projects\MAE

# fetch repository as zip archive
#shallow_clone: true                 # default is "false"

# set clone depth
#clone_depth: 1                      # clone entire repository history if not defined

environment:
  matrix:
    - PACKAGE_MANAGER: MSYS2
      INSTALL_COMMAND: ".appveyor\\msys2-install.bat"
      BUILD_COMMAND: ".appveyor\\msys2-build.bat"
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      MPREFIX: "/mingw64/"
    - PACKAGE_MANAGER: VCPKG
      VCPKG_DEFAULT_TRIPLET: x64-windows
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      INSTALL_COMMAND: ".appveyor\\vcpkg-install.bat"
      BUILD_COMMAND: ".appveyor\\vcpkg-build.bat"


# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x64
#  - x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# build cache to preserve files/folders between builds
cache: c:\tools\vcpkg\installed\

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cmd: '%INSTALL_COMMAND%'

#---------------------------------#
#       build configuration       #
#---------------------------------#


# scripts to run before build
before_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: '%BUILD_COMMAND%'

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
