/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class CancellationSymbol extends ISymbol {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public CancellationSymbol(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.CancellationSymbol_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CancellationSymbol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_CancellationSymbol(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CancellationSymbol(ECancel cancel) {
    this(MaeJavaJNI.new_CancellationSymbol(cancel.swigValue()), true);
  }

  public ECancel getCancel() {
    return ECancel.swigToEnum(MaeJavaJNI.CancellationSymbol_getCancel(swigCPtr, this));
  }

  public boolean equals(ISymbol a) {
    return MaeJavaJNI.CancellationSymbol_equals(swigCPtr, this, ISymbol.getCPtr(a), a);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.CancellationSymbol_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.CancellationSymbol_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.CancellationSymbol_xml__SWIG_2(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaeJavaJNI.CancellationSymbol_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaeJavaJNI.CancellationSymbol_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public String str() {
    return MaeJavaJNI.CancellationSymbol_str(swigCPtr, this);
  }

}
