/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class ColumnDefinitionVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ColumnDefinitionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColumnDefinitionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_ColumnDefinitionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ColumnDefinitionVector() {
    this(MaeJavaJNI.new_ColumnDefinitionVector__SWIG_0(), true);
  }

  public ColumnDefinitionVector(long n) {
    this(MaeJavaJNI.new_ColumnDefinitionVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.ColumnDefinitionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.ColumnDefinitionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.ColumnDefinitionVector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return MaeJavaJNI.ColumnDefinitionVector_empty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.ColumnDefinitionVector_clear(swigCPtr, this);
  }

  public void pushBack(ColumnDefinition x) {
    MaeJavaJNI.ColumnDefinitionVector_pushBack(swigCPtr, this, ColumnDefinition.getCPtr(x), x);
  }

  public ColumnDefinition get(int i) {
    long cPtr = MaeJavaJNI.ColumnDefinitionVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ColumnDefinition(cPtr, true);
  }

  public void set(int i, ColumnDefinition val) {
    MaeJavaJNI.ColumnDefinitionVector_set(swigCPtr, this, i, ColumnDefinition.getCPtr(val), val);
  }

}
