/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class default_limb extends i_limb {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected default_limb(long cPtr, boolean cMemoryOwn) {
    super(w_e_boneJNI.default_limb_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(default_limb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        w_e_boneJNI.delete_default_limb(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public default_limb(e_limb limb) {
    this(w_e_boneJNI.new_default_limb(limb.swigValue()), true);
  }

  public e_limb get_limb() {
    return e_limb.swigToEnum(w_e_boneJNI.default_limb_get_limb(swigCPtr, this));
  }

  public String xml(long indent, String namesp) {
    return w_e_boneJNI.default_limb_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return w_e_boneJNI.default_limb_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return w_e_boneJNI.default_limb_xml__SWIG_2(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return w_e_boneJNI.default_limb_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return w_e_boneJNI.default_limb_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public boolean equals(i_part a) {
    return w_e_boneJNI.default_limb_equals__SWIG_0(swigCPtr, this, i_part.getCPtr(a), a);
  }

  public boolean equals(i_limb a) {
    return w_e_boneJNI.default_limb_equals__SWIG_1(swigCPtr, this, i_limb.getCPtr(a), a);
  }

}
