/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class e_dynamic_vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected e_dynamic_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(e_dynamic_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaejavaJNI.delete_e_dynamic_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public e_dynamic_vector() {
    this(MaejavaJNI.new_e_dynamic_vector__SWIG_0(), true);
  }

  public e_dynamic_vector(long n) {
    this(MaejavaJNI.new_e_dynamic_vector__SWIG_1(n), true);
  }

  public long size() {
    return MaejavaJNI.e_dynamic_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaejavaJNI.e_dynamic_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaejavaJNI.e_dynamic_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MaejavaJNI.e_dynamic_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MaejavaJNI.e_dynamic_vector_clear(swigCPtr, this);
  }

  public void add(e_dynamic x) {
    MaejavaJNI.e_dynamic_vector_add(swigCPtr, this, x.swigValue());
  }

  public e_dynamic get(int i) {
    return e_dynamic.swigToEnum(MaejavaJNI.e_dynamic_vector_get(swigCPtr, this, i));
  }

  public void set(int i, e_dynamic val) {
    MaejavaJNI.e_dynamic_vector_set(swigCPtr, this, i, val.swigValue());
  }

}
