/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class e_fl_direction {
  public final static e_fl_direction INVALID = new e_fl_direction("INVALID", w_e_boneJNI.INVALID_get());
  public final static e_fl_direction P_H = new e_fl_direction("P_H");
  public final static e_fl_direction P_M = new e_fl_direction("P_M");
  public final static e_fl_direction P_L = new e_fl_direction("P_L");
  public final static e_fl_direction L_H = new e_fl_direction("L_H");
  public final static e_fl_direction L_M = new e_fl_direction("L_M");
  public final static e_fl_direction L_L = new e_fl_direction("L_L");
  public final static e_fl_direction D_F_L_H = new e_fl_direction("D_F_L_H");
  public final static e_fl_direction D_F_L_M = new e_fl_direction("D_F_L_M");
  public final static e_fl_direction D_F_L_L = new e_fl_direction("D_F_L_L");
  public final static e_fl_direction F_L_H = new e_fl_direction("F_L_H");
  public final static e_fl_direction F_L_M = new e_fl_direction("F_L_M");
  public final static e_fl_direction F_L_L = new e_fl_direction("F_L_L");
  public final static e_fl_direction F_R_H = new e_fl_direction("F_R_H");
  public final static e_fl_direction F_R_M = new e_fl_direction("F_R_M");
  public final static e_fl_direction F_R_L = new e_fl_direction("F_R_L");
  public final static e_fl_direction D_F_R_H = new e_fl_direction("D_F_R_H");
  public final static e_fl_direction D_F_R_M = new e_fl_direction("D_F_R_M");
  public final static e_fl_direction D_F_R_L = new e_fl_direction("D_F_R_L");
  public final static e_fl_direction R_H = new e_fl_direction("R_H");
  public final static e_fl_direction R_M = new e_fl_direction("R_M");
  public final static e_fl_direction R_L = new e_fl_direction("R_L");
  public final static e_fl_direction D_B_R_H = new e_fl_direction("D_B_R_H");
  public final static e_fl_direction D_B_R_M = new e_fl_direction("D_B_R_M");
  public final static e_fl_direction D_B_R_L = new e_fl_direction("D_B_R_L");
  public final static e_fl_direction B_R_H = new e_fl_direction("B_R_H");
  public final static e_fl_direction B_R_M = new e_fl_direction("B_R_M");
  public final static e_fl_direction B_R_L = new e_fl_direction("B_R_L");
  public final static e_fl_direction B_L_H = new e_fl_direction("B_L_H");
  public final static e_fl_direction B_L_M = new e_fl_direction("B_L_M");
  public final static e_fl_direction B_L_L = new e_fl_direction("B_L_L");
  public final static e_fl_direction D_B_L_H = new e_fl_direction("D_B_L_H");
  public final static e_fl_direction D_B_L_M = new e_fl_direction("D_B_L_M");
  public final static e_fl_direction D_B_L_L = new e_fl_direction("D_B_L_L");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static e_fl_direction swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + e_fl_direction.class + " with value " + swigValue);
  }

  private e_fl_direction(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private e_fl_direction(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private e_fl_direction(String swigName, e_fl_direction swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static e_fl_direction[] swigValues = { INVALID, P_H, P_M, P_L, L_H, L_M, L_L, D_F_L_H, D_F_L_M, D_F_L_L, F_L_H, F_L_M, F_L_L, F_R_H, F_R_M, F_R_L, D_F_R_H, D_F_R_M, D_F_R_L, R_H, R_M, R_L, D_B_R_H, D_B_R_M, D_B_R_L, B_R_H, B_R_M, B_R_L, B_L_H, B_L_M, B_L_L, D_B_L_H, D_B_L_M, D_B_L_L };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

