/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class e_limb_c {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected e_limb_c(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(e_limb_c obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        maeJNI.delete_e_limb_c(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String str(e_limb limb) {
    return maeJNI.e_limb_c_str(limb.swigValue());
  }

  public static e_limb_vector vec() {
    return new e_limb_vector(maeJNI.e_limb_c_vec(), true);
  }

  public static e_limb parse(String str) {
    return e_limb.swigToEnum(maeJNI.e_limb_c_parse(str));
  }

  public e_limb_c() {
    this(maeJNI.new_e_limb_c(), true);
  }

}
