/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class EArea {
  public final static EArea NONE_AREA = new EArea("NONE_AREA");
  public final static EArea HEAD = new EArea("HEAD");
  public final static EArea CHEST = new EArea("CHEST");
  public final static EArea WAIST = new EArea("WAIST");
  public final static EArea PELVIS = new EArea("PELVIS");
  public final static EArea TORSO = new EArea("TORSO");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EArea swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EArea.class + " with value " + swigValue);
  }

  private EArea(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EArea(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EArea(String swigName, EArea swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EArea[] swigValues = { NONE_AREA, HEAD, CHEST, WAIST, PELVIS, TORSO };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

