/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class ECancel {
  public final static ECancel NONE_CANCEL = new ECancel("NONE_CANCEL");
  public final static ECancel BACK_NORMAL = new ECancel("BACK_NORMAL");
  public final static ECancel RELEASE_CONTACT = new ECancel("RELEASE_CONTACT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ECancel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ECancel.class + " with value " + swigValue);
  }

  private ECancel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ECancel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ECancel(String swigName, ECancel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ECancel[] swigValues = { NONE_CANCEL, BACK_NORMAL, RELEASE_CONTACT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

