/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class ERelationshipType {
  public final static ERelationshipType NONE_RELATIONSHIP_TYPE = new ERelationshipType("NONE_RELATIONSHIP_TYPE");
  public final static ERelationshipType ADDRESS = new ERelationshipType("ADDRESS");
  public final static ERelationshipType NEAR = new ERelationshipType("NEAR");
  public final static ERelationshipType TOUCH = new ERelationshipType("TOUCH");
  public final static ERelationshipType SUPPORT = new ERelationshipType("SUPPORT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ERelationshipType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ERelationshipType.class + " with value " + swigValue);
  }

  private ERelationshipType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ERelationshipType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ERelationshipType(String swigName, ERelationshipType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ERelationshipType[] swigValues = { NONE_RELATIONSHIP_TYPE, ADDRESS, NEAR, TOUCH, SUPPORT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

