/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class ESpaceDirection {
  public final static ESpaceDirection NONE_SPACE_DIRECTION = new ESpaceDirection("NONE_SPACE_DIRECTION");
  public final static ESpaceDirection LEFT = new ESpaceDirection("LEFT");
  public final static ESpaceDirection FRONT_LEFT = new ESpaceDirection("FRONT_LEFT");
  public final static ESpaceDirection FRONT = new ESpaceDirection("FRONT");
  public final static ESpaceDirection FRONT_RIGHT = new ESpaceDirection("FRONT_RIGHT");
  public final static ESpaceDirection RIGHT = new ESpaceDirection("RIGHT");
  public final static ESpaceDirection BACK_RIGHT = new ESpaceDirection("BACK_RIGHT");
  public final static ESpaceDirection BACK = new ESpaceDirection("BACK");
  public final static ESpaceDirection BACK_LEFT = new ESpaceDirection("BACK_LEFT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ESpaceDirection swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ESpaceDirection.class + " with value " + swigValue);
  }

  private ESpaceDirection(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ESpaceDirection(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ESpaceDirection(String swigName, ESpaceDirection swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ESpaceDirection[] swigValues = { NONE_SPACE_DIRECTION, LEFT, FRONT_LEFT, FRONT, FRONT_RIGHT, RIGHT, BACK_RIGHT, BACK, BACK_LEFT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

