/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class fl_skel_laban_movement_controller {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected fl_skel_laban_movement_controller(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fl_skel_laban_movement_controller obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        w_e_boneJNI.delete_fl_skel_laban_movement_controller(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t imd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts, int pose_buffer_size, double framerate, boolean debug) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_0(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t.getCPtr(imd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts, pose_buffer_size, framerate, debug), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t imd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts, int pose_buffer_size, double framerate) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_1(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t.getCPtr(imd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts, pose_buffer_size, framerate), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t imd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts, int pose_buffer_size) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_2(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t.getCPtr(imd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts, pose_buffer_size), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t imd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_3(SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t.getCPtr(imd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t ipd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t isg, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts, int pose_buffer_size, double framerate, boolean debug) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_4(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t.getCPtr(ipd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t.getCPtr(isg), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts, pose_buffer_size, framerate, debug), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t ipd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t isg, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts, int pose_buffer_size, double framerate) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_5(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t.getCPtr(ipd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t.getCPtr(isg), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts, pose_buffer_size, framerate), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t ipd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t isg, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts, int pose_buffer_size) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_6(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t.getCPtr(ipd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t.getCPtr(isg), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts, pose_buffer_size), true);
  }

  public fl_skel_laban_movement_controller(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t ipd, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t isg, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t isr, bone_vector body_parts) {
    this(w_e_boneJNI.new_fl_skel_laban_movement_controller__SWIG_7(SWIGTYPE_p_std__shared_ptrT_mae__i_pose_detectorT_mae__fl__fl_skeleton_t_t.getCPtr(ipd), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_generatorT_mae__fl__laban__laban_sequence_t_t.getCPtr(isg), SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t.getCPtr(isr), bone_vector.getCPtr(body_parts), body_parts), true);
  }

  public void next_frame(int timestamp, SWIGTYPE_p_std__shared_ptrT_mae__fl__fl_skeleton_t skeleton) {
    w_e_boneJNI.fl_skel_laban_movement_controller_next_frame(swigCPtr, this, timestamp, SWIGTYPE_p_std__shared_ptrT_mae__fl__fl_skeleton_t.getCPtr(skeleton));
  }

  public void register_sequence(SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t sequence) {
    w_e_boneJNI.fl_skel_laban_movement_controller_register_sequence(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t.getCPtr(sequence));
  }

  public void deregister_sequence(SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t sequence) {
    w_e_boneJNI.fl_skel_laban_movement_controller_deregister_sequence(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t.getCPtr(sequence));
  }

  public void clear_registered_sequences() {
    w_e_boneJNI.fl_skel_laban_movement_controller_clear_registered_sequences(swigCPtr, this);
  }

  public void set_no_buffer_size_update(boolean updates) {
    w_e_boneJNI.fl_skel_laban_movement_controller_set_no_buffer_size_update(swigCPtr, this, updates);
  }

  public void clear_buffer() {
    w_e_boneJNI.fl_skel_laban_movement_controller_clear_buffer(swigCPtr, this);
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t get_current_sequence() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t(w_e_boneJNI.fl_skel_laban_movement_controller_get_current_sequence(swigCPtr, this), true);
  }

  public void add_listener(i_pose_listener pose_listener) {
    w_e_boneJNI.fl_skel_laban_movement_controller_add_listener__SWIG_0(swigCPtr, this, i_pose_listener.getCPtr(pose_listener), pose_listener);
  }

  public void remove_listener(i_pose_listener pose_listener) {
    w_e_boneJNI.fl_skel_laban_movement_controller_remove_listener__SWIG_0(swigCPtr, this, i_pose_listener.getCPtr(pose_listener), pose_listener);
  }

  public void add_listener(SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_listenerT_mae__fl__laban__laban_sequence_t_t sequence_listener) {
    w_e_boneJNI.fl_skel_laban_movement_controller_add_listener__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_listenerT_mae__fl__laban__laban_sequence_t_t.getCPtr(sequence_listener));
  }

  public void remove_listener(SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_listenerT_mae__fl__laban__laban_sequence_t_t sequence_listener) {
    w_e_boneJNI.fl_skel_laban_movement_controller_remove_listener__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_listenerT_mae__fl__laban__laban_sequence_t_t.getCPtr(sequence_listener));
  }

  public void add_listener(SWIGTYPE_p_std__shared_ptrT_mae__i_recognition_listenerT_mae__fl__laban__laban_sequence_t_t recognition_listener) {
    w_e_boneJNI.fl_skel_laban_movement_controller_add_listener__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__i_recognition_listenerT_mae__fl__laban__laban_sequence_t_t.getCPtr(recognition_listener));
  }

  public void remove_listener(SWIGTYPE_p_std__shared_ptrT_mae__i_recognition_listenerT_mae__fl__laban__laban_sequence_t_t recognition_listener) {
    w_e_boneJNI.fl_skel_laban_movement_controller_remove_listener__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_mae__i_recognition_listenerT_mae__fl__laban__laban_sequence_t_t.getCPtr(recognition_listener));
  }

  public void clear_listeners() {
    w_e_boneJNI.fl_skel_laban_movement_controller_clear_listeners(swigCPtr, this);
  }

  public void notify_sequence_listeners(int timestamp, SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t sequence) {
    w_e_boneJNI.fl_skel_laban_movement_controller_notify_sequence_listeners(swigCPtr, this, timestamp, SWIGTYPE_p_std__shared_ptrT_mae__fl__laban__laban_sequence_t.getCPtr(sequence));
  }

  public void notify_recognition_listeners(int timestamp, SWIGTYPE_p_std__vectorT_std__shared_ptrT_mae__fl__laban__laban_sequence_t_t sequences) {
    w_e_boneJNI.fl_skel_laban_movement_controller_notify_recognition_listeners(swigCPtr, this, timestamp, SWIGTYPE_p_std__vectorT_std__shared_ptrT_mae__fl__laban__laban_sequence_t_t.getCPtr(sequences));
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t get_movement_detector() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__i_movement_detectorT_mae__fl__fl_skeleton_mae__fl__laban__laban_sequence_t_t(w_e_boneJNI.fl_skel_laban_movement_controller_get_movement_detector(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t get_sequence_recognizer() {
    return new SWIGTYPE_p_std__shared_ptrT_mae__i_sequence_recognizerT_mae__fl__laban__laban_sequence_t_t(w_e_boneJNI.fl_skel_laban_movement_controller_get_sequence_recognizer(swigCPtr, this), true);
  }

}
