/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class general_enriched_pose extends general_pose {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected general_enriched_pose(long cPtr, boolean cMemoryOwn) {
    super(maeJNI.general_enriched_pose_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(general_enriched_pose obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        maeJNI.delete_general_enriched_pose(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    maeJNI.general_enriched_pose_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    maeJNI.general_enriched_pose_change_ownership(this, swigCPtr, true);
  }

  public general_enriched_pose() {
    this(maeJNI.new_general_enriched_pose__SWIG_0(), true);
    maeJNI.general_enriched_pose_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public general_enriched_pose(general_pose pose) {
    this(maeJNI.new_general_enriched_pose__SWIG_1(general_pose.getCPtr(pose), pose), true);
    maeJNI.general_enriched_pose_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void set_key_pose(int body_part, boolean is_key_pose) {
    if (getClass() == general_enriched_pose.class) maeJNI.general_enriched_pose_set_key_pose(swigCPtr, this, body_part, is_key_pose); else maeJNI.general_enriched_pose_set_key_poseSwigExplicitgeneral_enriched_pose(swigCPtr, this, body_part, is_key_pose);
  }

  public boolean is_key_pose(int body_part) {
    return (getClass() == general_enriched_pose.class) ? maeJNI.general_enriched_pose_is_key_pose(swigCPtr, this, body_part) : maeJNI.general_enriched_pose_is_key_poseSwigExplicitgeneral_enriched_pose(swigCPtr, this, body_part);
  }

  public void set_in_motion(int body_part, boolean is_in_motion) {
    if (getClass() == general_enriched_pose.class) maeJNI.general_enriched_pose_set_in_motion(swigCPtr, this, body_part, is_in_motion); else maeJNI.general_enriched_pose_set_in_motionSwigExplicitgeneral_enriched_pose(swigCPtr, this, body_part, is_in_motion);
  }

  public boolean is_in_motion(int body_part) {
    return (getClass() == general_enriched_pose.class) ? maeJNI.general_enriched_pose_is_in_motion(swigCPtr, this, body_part) : maeJNI.general_enriched_pose_is_in_motionSwigExplicitgeneral_enriched_pose(swigCPtr, this, body_part);
  }

}
