/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class i_dynamics_sign {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public i_dynamics_sign(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(i_dynamics_sign obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaejavaJNI.delete_i_dynamics_sign(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(i_dynamics_sign a) {
    return MaejavaJNI.i_dynamics_sign_equals(swigCPtr, this, i_dynamics_sign.getCPtr(a), a);
  }

  public String xml(long indent, String namesp) {
    return MaejavaJNI.i_dynamics_sign_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaejavaJNI.i_dynamics_sign_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaejavaJNI.i_dynamics_sign_xml__SWIG_2(swigCPtr, this);
  }

}
