/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class i_mov_vector_vector_dec_val_vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected i_mov_vector_vector_dec_val_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(i_mov_vector_vector_dec_val_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_i_mov_vector_vector_dec_val_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public i_mov_vector_vector_dec_val_vector() {
    this(MaeJavaJNI.new_i_mov_vector_vector_dec_val_vector__SWIG_0(), true);
  }

  public i_mov_vector_vector_dec_val_vector(long n) {
    this(MaeJavaJNI.new_i_mov_vector_vector_dec_val_vector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.i_mov_vector_vector_dec_val_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.i_mov_vector_vector_dec_val_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.i_mov_vector_vector_dec_val_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MaeJavaJNI.i_mov_vector_vector_dec_val_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.i_mov_vector_vector_dec_val_vector_clear(swigCPtr, this);
  }

  public void add(i_mov_vector_vector_dec_val x) {
    MaeJavaJNI.i_mov_vector_vector_dec_val_vector_add(swigCPtr, this, i_mov_vector_vector_dec_val.getCPtr(x));
  }

  public i_mov_vector_vector_dec_val get(int i) {
    long cPtr = MaeJavaJNI.i_mov_vector_vector_dec_val_vector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new i_mov_vector_vector_dec_val(cPtr, true);
  }

  public void set(int i, i_mov_vector_vector_dec_val val) {
    MaeJavaJNI.i_mov_vector_vector_dec_val_vector_set(swigCPtr, this, i, i_mov_vector_vector_dec_val.getCPtr(val));
  }

}
