/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class i_mov_vector_vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected i_mov_vector_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(i_mov_vector_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        w_e_boneJNI.delete_i_mov_vector_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public i_mov_vector_vector() {
    this(w_e_boneJNI.new_i_mov_vector_vector__SWIG_0(), true);
  }

  public i_mov_vector_vector(long n) {
    this(w_e_boneJNI.new_i_mov_vector_vector__SWIG_1(n), true);
  }

  public long size() {
    return w_e_boneJNI.i_mov_vector_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return w_e_boneJNI.i_mov_vector_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    w_e_boneJNI.i_mov_vector_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return w_e_boneJNI.i_mov_vector_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    w_e_boneJNI.i_mov_vector_vector_clear(swigCPtr, this);
  }

  public void add(i_mov_vector x) {
    w_e_boneJNI.i_mov_vector_vector_add(swigCPtr, this, i_mov_vector.getCPtr(x), x);
  }

  public i_mov_vector get(int i) {
    return new i_mov_vector(w_e_boneJNI.i_mov_vector_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, i_mov_vector val) {
    w_e_boneJNI.i_mov_vector_vector_set(swigCPtr, this, i, i_mov_vector.getCPtr(val), val);
  }

}
