/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class IPoseListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IPoseListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IPoseListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_IPoseListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onPose(int timestamp, GeneralPose pose) {
    MaeJavaJNI.IPoseListener_onPose(swigCPtr, this, timestamp, GeneralPose.getCPtr(pose), pose);
  }

}
