/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class joint_part extends i_endpoint {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected joint_part(long cPtr, boolean cMemoryOwn) {
    super(maeJNI.joint_part_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(joint_part obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        maeJNI.delete_joint_part(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    maeJNI.joint_part_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    maeJNI.joint_part_change_ownership(this, swigCPtr, true);
  }

  public joint_part(e_joint joint) {
    this(maeJNI.new_joint_part(joint.swigValue()), true);
    maeJNI.joint_part_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public e_joint get_joint() {
    return e_joint.swigToEnum(maeJNI.joint_part_get_joint(swigCPtr, this));
  }

  public String xml(long indent, String namesp) {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_xml__SWIG_0(swigCPtr, this, indent, namesp) : maeJNI.joint_part_xmlSwigExplicitjoint_part__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_xml__SWIG_1(swigCPtr, this, indent) : maeJNI.joint_part_xmlSwigExplicitjoint_part__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_xml__SWIG_2(swigCPtr, this) : maeJNI.joint_part_xmlSwigExplicitjoint_part__SWIG_2(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left) : maeJNI.joint_part_svgSwigExplicitjoint_part__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height) : maeJNI.joint_part_svgSwigExplicitjoint_part__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public i_endpoint get_fixed_end() {
    long cPtr = (getClass() == joint_part.class) ? maeJNI.joint_part_get_fixed_end(swigCPtr, this) : maeJNI.joint_part_get_fixed_endSwigExplicitjoint_part(swigCPtr, this);
    return (cPtr == 0) ? null : new i_endpoint(cPtr, true);
  }

  public boolean equals(i_part a) {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_equals__SWIG_0(swigCPtr, this, i_part.getCPtr(a), a) : maeJNI.joint_part_equalsSwigExplicitjoint_part__SWIG_0(swigCPtr, this, i_part.getCPtr(a), a);
  }

  public boolean equals(i_endpoint a) {
    return (getClass() == joint_part.class) ? maeJNI.joint_part_equals__SWIG_1(swigCPtr, this, i_endpoint.getCPtr(a), a) : maeJNI.joint_part_equalsSwigExplicitjoint_part__SWIG_1(swigCPtr, this, i_endpoint.getCPtr(a), a);
  }

}
