/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class joint_part extends i_endpoint {
  private long swigCPtr;

  protected joint_part(long cPtr, boolean cMemoryOwn) {
    super(w_e_boneJNI.joint_part_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(joint_part obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        w_e_boneJNI.delete_joint_part(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public joint_part(e_joint joint) {
    this(w_e_boneJNI.new_joint_part(joint.swigValue()), true);
  }

  public e_joint get_joint() {
    return e_joint.swigToEnum(w_e_boneJNI.joint_part_get_joint(swigCPtr, this));
  }

  public String xml(long indent, String namesp) {
    return w_e_boneJNI.joint_part_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return w_e_boneJNI.joint_part_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return w_e_boneJNI.joint_part_xml__SWIG_2(swigCPtr, this);
  }

  public i_endpoint get_fixed_end() {
    long cPtr = w_e_boneJNI.joint_part_get_fixed_end(swigCPtr, this);
    return (cPtr == 0) ? null : new i_endpoint(cPtr, true);
  }

  public boolean equals(i_part a) {
    return w_e_boneJNI.joint_part_equals__SWIG_0(swigCPtr, this, i_part.getCPtr(a), a);
  }

  public boolean equals(i_endpoint a) {
    return w_e_boneJNI.joint_part_equals__SWIG_1(swigCPtr, this, i_endpoint.getCPtr(a), a);
  }

}
