/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class laban_sequence_vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected laban_sequence_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(laban_sequence_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        w_e_boneJNI.delete_laban_sequence_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public laban_sequence_vector() {
    this(w_e_boneJNI.new_laban_sequence_vector__SWIG_0(), true);
  }

  public laban_sequence_vector(long n) {
    this(w_e_boneJNI.new_laban_sequence_vector__SWIG_1(n), true);
  }

  public long size() {
    return w_e_boneJNI.laban_sequence_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return w_e_boneJNI.laban_sequence_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    w_e_boneJNI.laban_sequence_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return w_e_boneJNI.laban_sequence_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    w_e_boneJNI.laban_sequence_vector_clear(swigCPtr, this);
  }

  public void add(laban_sequence x) {
    w_e_boneJNI.laban_sequence_vector_add(swigCPtr, this, laban_sequence.getCPtr(x), x);
  }

  public laban_sequence get(int i) {
    long cPtr = w_e_boneJNI.laban_sequence_vector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new laban_sequence(cPtr, true);
  }

  public void set(int i, laban_sequence val) {
    w_e_boneJNI.laban_sequence_vector_set(swigCPtr, this, i, laban_sequence.getCPtr(val), val);
  }

}
