/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class LabanSequenceSequenceGenerator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public LabanSequenceSequenceGenerator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LabanSequenceSequenceGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_LabanSequenceSequenceGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LabanSequence generateSequence(double framerate, EnrichedPoseList keyPoses, BoneVector bodyParts) {
    long cPtr = MaeJavaJNI.LabanSequenceSequenceGenerator_generateSequence(swigCPtr, this, framerate, EnrichedPoseList.getCPtr(keyPoses), keyPoses, BoneVector.getCPtr(bodyParts), bodyParts);
    return (cPtr == 0) ? null : new LabanSequence(cPtr, true);
  }

}
