/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class pin extends i_degree_sign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public pin(long cPtr, boolean cMemoryOwn) {
    super(MaejavaJNI.pin_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(pin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaejavaJNI.delete_pin(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public pin(e_level level, int horizontal) {
    this(MaejavaJNI.new_pin(level.swigValue(), horizontal), true);
  }

  public e_level get_level() {
    return e_level.swigToEnum(MaejavaJNI.pin_get_level(swigCPtr, this));
  }

  public int get_horizontal() {
    return MaejavaJNI.pin_get_horizontal(swigCPtr, this);
  }

  public boolean equals(i_degree_sign a) {
    return MaejavaJNI.pin_equals(swigCPtr, this, i_degree_sign.getCPtr(a), a);
  }

  public String xml(long indent, String namesp, boolean print_type) {
    return MaejavaJNI.pin_xml__SWIG_0(swigCPtr, this, indent, namesp, print_type);
  }

  public String xml(long indent, String namesp) {
    return MaejavaJNI.pin_xml__SWIG_1(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaejavaJNI.pin_xml__SWIG_2(swigCPtr, this, indent);
  }

  public String xml() {
    return MaejavaJNI.pin_xml__SWIG_3(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaejavaJNI.pin_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaejavaJNI.pin_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

}
