/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class prop extends i_pre_sign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public prop(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.prop_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(prop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_prop(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public prop(String name, String description) {
    this(MaeJavaJNI.new_prop__SWIG_0(name, description), true);
  }

  public prop(String name) {
    this(MaeJavaJNI.new_prop__SWIG_1(name), true);
  }

  public String get_name() {
    return MaeJavaJNI.prop_get_name(swigCPtr, this);
  }

  public String get_description() {
    return MaeJavaJNI.prop_get_description(swigCPtr, this);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.prop_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.prop_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.prop_xml__SWIG_2(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaeJavaJNI.prop_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaeJavaJNI.prop_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public boolean equals(i_pre_sign a) {
    return MaeJavaJNI.prop_equals(swigCPtr, this, i_pre_sign.getCPtr(a), a);
  }

}
