/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class space_measurement extends i_degree_sign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  protected space_measurement(long cPtr, boolean cMemoryOwn) {
    super(w_e_boneJNI.space_measurement_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(space_measurement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        w_e_boneJNI.delete_space_measurement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public space_measurement(e_space type, long degree, e_space_direction direction) {
    this(w_e_boneJNI.new_space_measurement__SWIG_0(type.swigValue(), degree, direction.swigValue()), true);
  }

  public space_measurement(e_space type, long degree) {
    this(w_e_boneJNI.new_space_measurement__SWIG_1(type.swigValue(), degree), true);
  }

  public e_space get_type() {
    return e_space.swigToEnum(w_e_boneJNI.space_measurement_get_type(swigCPtr, this));
  }

  public long get_degree() {
    return w_e_boneJNI.space_measurement_get_degree(swigCPtr, this);
  }

  public e_space_direction get_direction() {
    return e_space_direction.swigToEnum(w_e_boneJNI.space_measurement_get_direction(swigCPtr, this));
  }

  public boolean equals(i_degree_sign a) {
    return w_e_boneJNI.space_measurement_equals(swigCPtr, this, i_degree_sign.getCPtr(a), a);
  }

  public String xml(long indent, String namesp) {
    return w_e_boneJNI.space_measurement_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return w_e_boneJNI.space_measurement_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return w_e_boneJNI.space_measurement_xml__SWIG_2(swigCPtr, this);
  }

  public String str() {
    return w_e_boneJNI.space_measurement_str(swigCPtr, this);
  }

}
