/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class string_vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected string_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(string_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaejavaJNI.delete_string_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public string_vector() {
    this(MaejavaJNI.new_string_vector__SWIG_0(), true);
  }

  public string_vector(long n) {
    this(MaejavaJNI.new_string_vector__SWIG_1(n), true);
  }

  public long size() {
    return MaejavaJNI.string_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaejavaJNI.string_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaejavaJNI.string_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MaejavaJNI.string_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MaejavaJNI.string_vector_clear(swigCPtr, this);
  }

  public void add(String x) {
    MaejavaJNI.string_vector_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return MaejavaJNI.string_vector_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    MaejavaJNI.string_vector_set(swigCPtr, this, i, val);
  }

}
