/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class vec3d {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public vec3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(vec3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaejavaJNI.delete_vec3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vec3d() {
    this(MaejavaJNI.new_vec3d__SWIG_0(), true);
  }

  public vec3d(double x, double y, double z) {
    this(MaejavaJNI.new_vec3d__SWIG_1(x, y, z), true);
  }

  public void set_x(double x) {
    MaejavaJNI.vec3d_set_x(swigCPtr, this, x);
  }

  public double get_x() {
    return MaejavaJNI.vec3d_get_x(swigCPtr, this);
  }

  public void set_y(double y) {
    MaejavaJNI.vec3d_set_y(swigCPtr, this, y);
  }

  public double get_y() {
    return MaejavaJNI.vec3d_get_y(swigCPtr, this);
  }

  public void set_z(double z) {
    MaejavaJNI.vec3d_set_z(swigCPtr, this, z);
  }

  public double get_z() {
    return MaejavaJNI.vec3d_get_z(swigCPtr, this);
  }

  public String str() {
    return MaejavaJNI.vec3d_str(swigCPtr, this);
  }

}
