/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class Vec3d {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Vec3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vec3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_Vec3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vec3d() {
    this(MaeJavaJNI.new_Vec3d__SWIG_0(), true);
  }

  public Vec3d(double x, double y, double z) {
    this(MaeJavaJNI.new_Vec3d__SWIG_1(x, y, z), true);
  }

  public void setX(double x) {
    MaeJavaJNI.Vec3d_setX(swigCPtr, this, x);
  }

  public double getX() {
    return MaeJavaJNI.Vec3d_getX(swigCPtr, this);
  }

  public void setY(double y) {
    MaeJavaJNI.Vec3d_setY(swigCPtr, this, y);
  }

  public double getY() {
    return MaeJavaJNI.Vec3d_getY(swigCPtr, this);
  }

  public void setZ(double z) {
    MaeJavaJNI.Vec3d_setZ(swigCPtr, this, z);
  }

  public double getZ() {
    return MaeJavaJNI.Vec3d_getZ(swigCPtr, this);
  }

  public String str() {
    return MaeJavaJNI.Vec3d_str(swigCPtr, this);
  }

}
