/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class AccentSign extends IDynamicsSign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public AccentSign(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.AccentSign_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(AccentSign obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_AccentSign(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AccentSign(long accent) {
    this(MaeJavaJNI.new_AccentSign(accent), true);
  }

  public long getAccent() {
    return MaeJavaJNI.AccentSign_getAccent(swigCPtr, this);
  }

  public boolean equals(IDynamicsSign a) {
    return MaeJavaJNI.AccentSign_equals(swigCPtr, this, IDynamicsSign.getCPtr(a), a);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.AccentSign_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.AccentSign_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.AccentSign_xml__SWIG_2(swigCPtr, this);
  }

  public static AccentSign castToAccentSign(IDynamicsSign base) {
    long cPtr = MaeJavaJNI.AccentSign_castToAccentSign(IDynamicsSign.getCPtr(base), base);
    return (cPtr == 0) ? null : new AccentSign(cPtr, true);
  }

}
