/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class BodyPart extends IPreSign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public BodyPart(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.BodyPart_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BodyPart obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_BodyPart(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BodyPart(ESide side, IPart part) {
    this(MaeJavaJNI.new_BodyPart(side.swigValue(), IPart.getCPtr(part), part), true);
  }

  public ESide getSide() {
    return ESide.swigToEnum(MaeJavaJNI.BodyPart_getSide(swigCPtr, this));
  }

  public IPart getPart() {
    long cPtr = MaeJavaJNI.BodyPart_getPart(swigCPtr, this);
    return (cPtr == 0) ? null : new IPart(cPtr, true);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.BodyPart_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.BodyPart_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.BodyPart_xml__SWIG_2(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaeJavaJNI.BodyPart_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaeJavaJNI.BodyPart_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public boolean equals(IPreSign a) {
    return MaeJavaJNI.BodyPart_equals(swigCPtr, this, IPreSign.getCPtr(a), a);
  }

  public static BodyPart castToBodyPart(IPreSign base) {
    long cPtr = MaeJavaJNI.BodyPart_castToBodyPart(IPreSign.getCPtr(base), base);
    return (cPtr == 0) ? null : new BodyPart(cPtr, true);
  }

}
