/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class BvhData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public BvhData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BvhData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_BvhData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BvhData() {
    this(MaeJavaJNI.new_BvhData__SWIG_0(), true);
  }

  public BvhData(GeneralSkeletonVector skeleton_data, double framerate) {
    this(MaeJavaJNI.new_BvhData__SWIG_1(GeneralSkeletonVector.getCPtr(skeleton_data), skeleton_data, framerate), true);
  }

  public void setSkeletonData(GeneralSkeletonVector skeleton_data) {
    MaeJavaJNI.BvhData_setSkeletonData(swigCPtr, this, GeneralSkeletonVector.getCPtr(skeleton_data), skeleton_data);
  }

  public GeneralSkeletonVector getSkeletonData() {
    return new GeneralSkeletonVector(MaeJavaJNI.BvhData_getSkeletonData(swigCPtr, this), true);
  }

  public void setFramerate(double framerate) {
    MaeJavaJNI.BvhData_setFramerate(swigCPtr, this, framerate);
  }

  public double getFramerate() {
    return MaeJavaJNI.BvhData_getFramerate(swigCPtr, this);
  }

}
