/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class EDynamic {
  public final static EDynamic NONE_DYNAMIC = new EDynamic("NONE_DYNAMIC");
  public final static EDynamic STRONG = new EDynamic("STRONG");
  public final static EDynamic GENTLE = new EDynamic("GENTLE");
  public final static EDynamic EMPHASIZED = new EDynamic("EMPHASIZED");
  public final static EDynamic RELAXED = new EDynamic("RELAXED");
  public final static EDynamic LIMP = new EDynamic("LIMP");
  public final static EDynamic UNEMPHASIZED = new EDynamic("UNEMPHASIZED");
  public final static EDynamic RESILIENT = new EDynamic("RESILIENT");
  public final static EDynamic VERY_RESILIENT = new EDynamic("VERY_RESILIENT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EDynamic swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EDynamic.class + " with value " + swigValue);
  }

  private EDynamic(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EDynamic(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EDynamic(String swigName, EDynamic swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EDynamic[] swigValues = { NONE_DYNAMIC, STRONG, GENTLE, EMPHASIZED, RELAXED, LIMP, UNEMPHASIZED, RESILIENT, VERY_RESILIENT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

