/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class EHandBoneVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public EHandBoneVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(EHandBoneVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_EHandBoneVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EHandBoneVector() {
    this(MaeJavaJNI.new_EHandBoneVector__SWIG_0(), true);
  }

  public EHandBoneVector(long n) {
    this(MaeJavaJNI.new_EHandBoneVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.EHandBoneVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.EHandBoneVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.EHandBoneVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MaeJavaJNI.EHandBoneVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.EHandBoneVector_clear(swigCPtr, this);
  }

  public void add(EHandBone x) {
    MaeJavaJNI.EHandBoneVector_add(swigCPtr, this, x.swigValue());
  }

  public EHandBone get(int i) {
    return EHandBone.swigToEnum(MaeJavaJNI.EHandBoneVector_get(swigCPtr, this, i));
  }

  public void set(int i, EHandBone val) {
    MaeJavaJNI.EHandBoneVector_set(swigCPtr, this, i, val.swigValue());
  }

}
