/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class EHandJointC {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public EHandJointC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(EHandJointC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_EHandJointC(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String str(EHandJoint joint) {
    return MaeJavaJNI.EHandJointC_str(joint.swigValue());
  }

  public static int toInt(EHandJoint joint) {
    return MaeJavaJNI.EHandJointC_toInt(joint.swigValue());
  }

  public static EHandJointVector vec() {
    return new EHandJointVector(MaeJavaJNI.EHandJointC_vec(), true);
  }

  public static boolean isDummy(EHandJoint joint) {
    return MaeJavaJNI.EHandJointC_isDummy(joint.swigValue());
  }

  public static boolean isPalm(EHandJoint joint) {
    return MaeJavaJNI.EHandJointC_isPalm(joint.swigValue());
  }

  public static EHandJoint parse(String str) {
    return EHandJoint.swigToEnum(MaeJavaJNI.EHandJointC_parse(str));
  }

  public EHandJointC() {
    this(MaeJavaJNI.new_EHandJointC(), true);
  }

}
