/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class EHandJointVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public EHandJointVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(EHandJointVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_EHandJointVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EHandJointVector() {
    this(MaeJavaJNI.new_EHandJointVector__SWIG_0(), true);
  }

  public EHandJointVector(long n) {
    this(MaeJavaJNI.new_EHandJointVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.EHandJointVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.EHandJointVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.EHandJointVector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return MaeJavaJNI.EHandJointVector_empty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.EHandJointVector_clear(swigCPtr, this);
  }

  public void pushBack(EHandJoint x) {
    MaeJavaJNI.EHandJointVector_pushBack(swigCPtr, this, x.swigValue());
  }

  public EHandJoint get(int i) {
    return EHandJoint.swigToEnum(MaeJavaJNI.EHandJointVector_get(swigCPtr, this, i));
  }

  public void set(int i, EHandJoint val) {
    MaeJavaJNI.EHandJointVector_set(swigCPtr, this, i, val.swigValue());
  }

}
