/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class EJoint {
  public final static EJoint NONE_JOINT = new EJoint("NONE_JOINT");
  public final static EJoint SHOULDER = new EJoint("SHOULDER");
  public final static EJoint ELBOW = new EJoint("ELBOW");
  public final static EJoint WRIST = new EJoint("WRIST");
  public final static EJoint HAND = new EJoint("HAND");
  public final static EJoint FINGERS = new EJoint("FINGERS");
  public final static EJoint HIP = new EJoint("HIP");
  public final static EJoint KNEE = new EJoint("KNEE");
  public final static EJoint ANKLE = new EJoint("ANKLE");
  public final static EJoint FOOT = new EJoint("FOOT");
  public final static EJoint TOES = new EJoint("TOES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EJoint swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EJoint.class + " with value " + swigValue);
  }

  private EJoint(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EJoint(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EJoint(String swigName, EJoint swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EJoint[] swigValues = { NONE_JOINT, SHOULDER, ELBOW, WRIST, HAND, FINGERS, HIP, KNEE, ANKLE, FOOT, TOES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

