/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class EKinectJointVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public EKinectJointVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(EKinectJointVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_EKinectJointVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EKinectJointVector() {
    this(MaeJavaJNI.new_EKinectJointVector__SWIG_0(), true);
  }

  public EKinectJointVector(long n) {
    this(MaeJavaJNI.new_EKinectJointVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.EKinectJointVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.EKinectJointVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.EKinectJointVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MaeJavaJNI.EKinectJointVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.EKinectJointVector_clear(swigCPtr, this);
  }

  public void add(EKinectJoint x) {
    MaeJavaJNI.EKinectJointVector_add(swigCPtr, this, x.swigValue());
  }

  public EKinectJoint get(int i) {
    return EKinectJoint.swigToEnum(MaeJavaJNI.EKinectJointVector_get(swigCPtr, this, i));
  }

  public void set(int i, EKinectJoint val) {
    MaeJavaJNI.EKinectJointVector_set(swigCPtr, this, i, val.swigValue());
  }

}
