/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class ELimbSideVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ELimbSideVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ELimbSideVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_ELimbSideVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ELimbSideVector() {
    this(MaeJavaJNI.new_ELimbSideVector__SWIG_0(), true);
  }

  public ELimbSideVector(long n) {
    this(MaeJavaJNI.new_ELimbSideVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.ELimbSideVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.ELimbSideVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.ELimbSideVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MaeJavaJNI.ELimbSideVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.ELimbSideVector_clear(swigCPtr, this);
  }

  public void add(ELimbSide x) {
    MaeJavaJNI.ELimbSideVector_add(swigCPtr, this, x.swigValue());
  }

  public ELimbSide get(int i) {
    return ELimbSide.swigToEnum(MaeJavaJNI.ELimbSideVector_get(swigCPtr, this, i));
  }

  public void set(int i, ELimbSide val) {
    MaeJavaJNI.ELimbSideVector_set(swigCPtr, this, i, val.swigValue());
  }

}
