/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public final class ELimb {
  public final static ELimb NONE_LIMB = new ELimb("NONE_LIMB");
  public final static ELimb ARM = new ELimb("ARM");
  public final static ELimb LEG = new ELimb("LEG");
  public final static ELimb NECK = new ELimb("NECK");
  public final static ELimb UPPER_ARM = new ELimb("UPPER_ARM");
  public final static ELimb LOWER_ARM = new ELimb("LOWER_ARM");
  public final static ELimb THIGH = new ELimb("THIGH");
  public final static ELimb LOWER_LEG = new ELimb("LOWER_LEG");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ELimb swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ELimb.class + " with value " + swigValue);
  }

  private ELimb(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ELimb(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ELimb(String swigName, ELimb swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ELimb[] swigValues = { NONE_LIMB, ARM, LEG, NECK, UPPER_ARM, LOWER_ARM, THIGH, LOWER_LEG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

