/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class EnrichedPoseList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public EnrichedPoseList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(EnrichedPoseList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_EnrichedPoseList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EnrichedPoseList() {
    this(MaeJavaJNI.new_EnrichedPoseList(), true);
  }

  public long size() {
    return MaeJavaJNI.EnrichedPoseList_size(swigCPtr, this);
  }

  public boolean empty() {
    return MaeJavaJNI.EnrichedPoseList_empty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.EnrichedPoseList_clear(swigCPtr, this);
  }

  public void pushBack(GeneralEnrichedPose x) {
    MaeJavaJNI.EnrichedPoseList_pushBack(swigCPtr, this, GeneralEnrichedPose.getCPtr(x), x);
  }

  public GeneralEnrichedPose get(int i) {
    long cPtr = MaeJavaJNI.EnrichedPoseList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new GeneralEnrichedPose(cPtr, true);
  }

}
