/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class FlPoseDetector extends FlSkeletonPoseDetector {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public FlPoseDetector(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.FlPoseDetector_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FlPoseDetector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_FlPoseDetector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FlPoseDetector(double hysteresis_val, boolean debug) {
    this(MaeJavaJNI.new_FlPoseDetector__SWIG_0(hysteresis_val, debug), true);
  }

  public FlPoseDetector(double hysteresis_val) {
    this(MaeJavaJNI.new_FlPoseDetector__SWIG_1(hysteresis_val), true);
  }

  public FlPoseDetector() {
    this(MaeJavaJNI.new_FlPoseDetector__SWIG_2(), true);
  }

  public void setHysteresisVal(double hysteresis_val) {
    MaeJavaJNI.FlPoseDetector_setHysteresisVal(swigCPtr, this, hysteresis_val);
  }

  public double getHysteresisVal() {
    return MaeJavaJNI.FlPoseDetector_getHysteresisVal(swigCPtr, this);
  }

  public GeneralPose pose(double framerate, FlSkeleton skeleton, BoneVector body_parts, GeneralPose previous_pose) {
    long cPtr = MaeJavaJNI.FlPoseDetector_pose(swigCPtr, this, framerate, FlSkeleton.getCPtr(skeleton), skeleton, BoneVector.getCPtr(body_parts), body_parts, GeneralPose.getCPtr(previous_pose), previous_pose);
    return (cPtr == 0) ? null : new GeneralPose(cPtr, true);
  }

  public GeneralPose vectorPose(FlSkeleton skeleton, BoneVector body_parts, GeneralPose previous_pose) {
    long cPtr = MaeJavaJNI.FlPoseDetector_vectorPose(swigCPtr, this, FlSkeleton.getCPtr(skeleton), skeleton, BoneVector.getCPtr(body_parts), body_parts, GeneralPose.getCPtr(previous_pose), previous_pose);
    return (cPtr == 0) ? null : new GeneralPose(cPtr, true);
  }

  public static double defaultHysteresisVal() {
    return MaeJavaJNI.FlPoseDetector_defaultHysteresisVal();
  }

  public void clearBuffer() {
    MaeJavaJNI.FlPoseDetector_clearBuffer(swigCPtr, this);
  }

}
