/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class IDegreeSign {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public IDegreeSign(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IDegreeSign obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_IDegreeSign(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(IDegreeSign a) {
    return MaeJavaJNI.IDegreeSign_equals(swigCPtr, this, IDegreeSign.getCPtr(a), a);
  }

  public String xml(long indent, String namesp, boolean print_type) {
    return MaeJavaJNI.IDegreeSign_xml__SWIG_0(swigCPtr, this, indent, namesp, print_type);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.IDegreeSign_xml__SWIG_1(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.IDegreeSign_xml__SWIG_2(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.IDegreeSign_xml__SWIG_3(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaeJavaJNI.IDegreeSign_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaeJavaJNI.IDegreeSign_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

}
