/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class IEndpoint extends IPart {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public IEndpoint(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.IEndpoint_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IEndpoint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_IEndpoint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.IEndpoint_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.IEndpoint_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.IEndpoint_xml__SWIG_2(swigCPtr, this);
  }

  public IEndpoint getFixedEnd() {
    long cPtr = MaeJavaJNI.IEndpoint_getFixedEnd(swigCPtr, this);
    return (cPtr == 0) ? null : new IEndpoint(cPtr, true);
  }

  public boolean equals(IPart a) {
    return MaeJavaJNI.IEndpoint_equals__SWIG_0(swigCPtr, this, IPart.getCPtr(a), a);
  }

  public boolean equals(IEndpoint a) {
    return MaeJavaJNI.IEndpoint_equals__SWIG_1(swigCPtr, this, IEndpoint.getCPtr(a), a);
  }

}
