/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class IMovementVectorVectorDecisionValueVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IMovementVectorVectorDecisionValueVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IMovementVectorVectorDecisionValueVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_IMovementVectorVectorDecisionValueVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IMovementVectorVectorDecisionValueVector() {
    this(MaeJavaJNI.new_IMovementVectorVectorDecisionValueVector__SWIG_0(), true);
  }

  public IMovementVectorVectorDecisionValueVector(long n) {
    this(MaeJavaJNI.new_IMovementVectorVectorDecisionValueVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.IMovementVectorVectorDecisionValueVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.IMovementVectorVectorDecisionValueVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.IMovementVectorVectorDecisionValueVector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return MaeJavaJNI.IMovementVectorVectorDecisionValueVector_empty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.IMovementVectorVectorDecisionValueVector_clear(swigCPtr, this);
  }

  public void pushBack(IMovementVectorVectorDecisionValue x) {
    MaeJavaJNI.IMovementVectorVectorDecisionValueVector_pushBack(swigCPtr, this, IMovementVectorVectorDecisionValue.getCPtr(x));
  }

  public IMovementVectorVectorDecisionValue get(int i) {
    long cPtr = MaeJavaJNI.IMovementVectorVectorDecisionValueVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new IMovementVectorVectorDecisionValue(cPtr, true);
  }

  public void set(int i, IMovementVectorVectorDecisionValue val) {
    MaeJavaJNI.IMovementVectorVectorDecisionValueVector_set(swigCPtr, this, i, IMovementVectorVectorDecisionValue.getCPtr(val));
  }

}
