/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class LabanSequenceVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public LabanSequenceVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LabanSequenceVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_LabanSequenceVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LabanSequenceVector() {
    this(MaeJavaJNI.new_LabanSequenceVector__SWIG_0(), true);
  }

  public LabanSequenceVector(long n) {
    this(MaeJavaJNI.new_LabanSequenceVector__SWIG_1(n), true);
  }

  public long size() {
    return MaeJavaJNI.LabanSequenceVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MaeJavaJNI.LabanSequenceVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MaeJavaJNI.LabanSequenceVector_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return MaeJavaJNI.LabanSequenceVector_empty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.LabanSequenceVector_clear(swigCPtr, this);
  }

  public void pushBack(LabanSequence x) {
    MaeJavaJNI.LabanSequenceVector_pushBack(swigCPtr, this, LabanSequence.getCPtr(x), x);
  }

  public LabanSequence get(int i) {
    long cPtr = MaeJavaJNI.LabanSequenceVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new LabanSequence(cPtr, true);
  }

  public void set(int i, LabanSequence val) {
    MaeJavaJNI.LabanSequenceVector_set(swigCPtr, this, i, LabanSequence.getCPtr(val), val);
  }

}
