/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class MsrSpec {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public MsrSpec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MsrSpec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_MsrSpec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MsrSpec(UIntIntMap id_map, Hierarchy hierarchy, long lines_per_joint, long pos_line_index) {
    this(MaeJavaJNI.new_MsrSpec(UIntIntMap.getCPtr(id_map), id_map, Hierarchy.getCPtr(hierarchy), hierarchy, lines_per_joint, pos_line_index), true);
  }

  public UIntIntMap getIdMap() {
    return new UIntIntMap(MaeJavaJNI.MsrSpec_getIdMap(swigCPtr, this), true);
  }

  public Hierarchy getHierarchy() {
    long cPtr = MaeJavaJNI.MsrSpec_getHierarchy(swigCPtr, this);
    return (cPtr == 0) ? null : new Hierarchy(cPtr, true);
  }

  public long getLinesPerJoint() {
    return MaeJavaJNI.MsrSpec_getLinesPerJoint(swigCPtr, this);
  }

  public long getPosLineIndex() {
    return MaeJavaJNI.MsrSpec_getPosLineIndex(swigCPtr, this);
  }

  public static MsrSpec defaultSpec() {
    long cPtr = MaeJavaJNI.MsrSpec_defaultSpec();
    return (cPtr == 0) ? null : new MsrSpec(cPtr, true);
  }

  public static MsrSpec defaultMsrSpec() {
    long cPtr = MaeJavaJNI.MsrSpec_defaultMsrSpec();
    return (cPtr == 0) ? null : new MsrSpec(cPtr, true);
  }

}
