/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class Pin extends IDegreeSign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public Pin(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.Pin_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Pin obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_Pin(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Pin(ELevel level, int horizontal) {
    this(MaeJavaJNI.new_Pin(level.swigValue(), horizontal), true);
  }

  public ELevel getLevel() {
    return ELevel.swigToEnum(MaeJavaJNI.Pin_getLevel(swigCPtr, this));
  }

  public int getHorizontal() {
    return MaeJavaJNI.Pin_getHorizontal(swigCPtr, this);
  }

  public boolean equals(IDegreeSign a) {
    return MaeJavaJNI.Pin_equals(swigCPtr, this, IDegreeSign.getCPtr(a), a);
  }

  public String xml(long indent, String namesp, boolean print_type) {
    return MaeJavaJNI.Pin_xml__SWIG_0(swigCPtr, this, indent, namesp, print_type);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.Pin_xml__SWIG_1(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.Pin_xml__SWIG_2(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.Pin_xml__SWIG_3(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaeJavaJNI.Pin_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaeJavaJNI.Pin_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public static Pin castToPin(IDegreeSign base) {
    long cPtr = MaeJavaJNI.Pin_castToPin(IDegreeSign.getCPtr(base), base);
    return (cPtr == 0) ? null : new Pin(cPtr, true);
  }

}
