/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class Prop extends IPreSign {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public Prop(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.Prop_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Prop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_Prop(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Prop(String name, String description) {
    this(MaeJavaJNI.new_Prop__SWIG_0(name, description), true);
  }

  public Prop(String name) {
    this(MaeJavaJNI.new_Prop__SWIG_1(name), true);
  }

  public String getName() {
    return MaeJavaJNI.Prop_getName(swigCPtr, this);
  }

  public String getDescription() {
    return MaeJavaJNI.Prop_getDescription(swigCPtr, this);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.Prop_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.Prop_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.Prop_xml__SWIG_2(swigCPtr, this);
  }

  public String svg(String identifier, double posx, double posy, double width, double height, boolean left) {
    return MaeJavaJNI.Prop_svg__SWIG_0(swigCPtr, this, identifier, posx, posy, width, height, left);
  }

  public String svg(String identifier, double posx, double posy, double width, double height) {
    return MaeJavaJNI.Prop_svg__SWIG_1(swigCPtr, this, identifier, posx, posy, width, height);
  }

  public boolean equals(IPreSign a) {
    return MaeJavaJNI.Prop_equals(swigCPtr, this, IPreSign.getCPtr(a), a);
  }

  public static Prop castToProp(IPreSign base) {
    long cPtr = MaeJavaJNI.Prop_castToProp(IPreSign.getCPtr(base), base);
    return (cPtr == 0) ? null : new Prop(cPtr, true);
  }

}
