/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class RoomDirection extends IMovement {
  private long swigCPtr;
  private boolean swigCMemOwnDerived;

  public RoomDirection(long cPtr, boolean cMemoryOwn) {
    super(MaeJavaJNI.RoomDirection_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RoomDirection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        MaeJavaJNI.delete_RoomDirection(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RoomDirection(long measure, double beat, Pin direction) {
    this(MaeJavaJNI.new_RoomDirection(measure, beat, Pin.getCPtr(direction), direction), true);
  }

  public int getColumn() {
    return MaeJavaJNI.RoomDirection_getColumn(swigCPtr, this);
  }

  public long getMeasure() {
    return MaeJavaJNI.RoomDirection_getMeasure(swigCPtr, this);
  }

  public double getBeat() {
    return MaeJavaJNI.RoomDirection_getBeat(swigCPtr, this);
  }

  public double getDuration() {
    return MaeJavaJNI.RoomDirection_getDuration(swigCPtr, this);
  }

  public Pin getDirection() {
    long cPtr = MaeJavaJNI.RoomDirection_getDirection(swigCPtr, this);
    return (cPtr == 0) ? null : new Pin(cPtr, true);
  }

  public boolean equals(IMovement a) {
    return MaeJavaJNI.RoomDirection_equals(swigCPtr, this, IMovement.getCPtr(a), a);
  }

  public boolean symbolEquals(IMovement a) {
    return MaeJavaJNI.RoomDirection_symbolEquals(swigCPtr, this, IMovement.getCPtr(a), a);
  }

  public String xml(long indent, String namesp) {
    return MaeJavaJNI.RoomDirection_xml__SWIG_0(swigCPtr, this, indent, namesp);
  }

  public String xml(long indent) {
    return MaeJavaJNI.RoomDirection_xml__SWIG_1(swigCPtr, this, indent);
  }

  public String xml() {
    return MaeJavaJNI.RoomDirection_xml__SWIG_2(swigCPtr, this);
  }

  public String svg(long im_width, long im_height, long max_column, long measures, long beats_per_measure) {
    return MaeJavaJNI.RoomDirection_svg(swigCPtr, this, im_width, im_height, max_column, measures, beats_per_measure);
  }

  public IMovement recreate(IntIntMap column_mapping, long measure, double beat, double duration) {
    long cPtr = MaeJavaJNI.RoomDirection_recreate(swigCPtr, this, IntIntMap.getCPtr(column_mapping), column_mapping, measure, beat, duration);
    return (cPtr == 0) ? null : new IMovement(cPtr, true);
  }

  public String str() {
    return MaeJavaJNI.RoomDirection_str(swigCPtr, this);
  }

  public static RoomDirection castToRoomDirection(IMovement base) {
    long cPtr = MaeJavaJNI.RoomDirection_castToRoomDirection(IMovement.getCPtr(base), base);
    return (cPtr == 0) ? null : new RoomDirection(cPtr, true);
  }

}
