/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package maejava;

public class StringBoolMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StringBoolMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StringBoolMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MaeJavaJNI.delete_StringBoolMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringBoolMap() {
    this(MaeJavaJNI.new_StringBoolMap__SWIG_0(), true);
  }

  public StringBoolMap(StringBoolMap arg0) {
    this(MaeJavaJNI.new_StringBoolMap__SWIG_1(StringBoolMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return MaeJavaJNI.StringBoolMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return MaeJavaJNI.StringBoolMap_empty(swigCPtr, this);
  }

  public void clear() {
    MaeJavaJNI.StringBoolMap_clear(swigCPtr, this);
  }

  public boolean get(String key) {
    return MaeJavaJNI.StringBoolMap_get(swigCPtr, this, key);
  }

  public void set(String key, boolean x) {
    MaeJavaJNI.StringBoolMap_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    MaeJavaJNI.StringBoolMap_del(swigCPtr, this, key);
  }

  public boolean hasKey(String key) {
    return MaeJavaJNI.StringBoolMap_hasKey(swigCPtr, this, key);
  }

}
